stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: python:slim
  script:
    - pip install -U jupyter-book
    - jupyter-book clean jupyterbook
    - jupyter-book build jupyterbook
  artifacts:
    paths:
      - jupyterbook/_build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv jupyterbook/_build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
