stages:
  - build
  - deploy

jupyter-build:
  stage: build
  image: python:slim
  script:
    - pip install -U jupyter-book
    - jupyter-book clean jupyterbook-de
    - jupyter-book build jupyterbook-de
    - jupyter-book clean jupyterbook-fr
    - jupyter-book build jupyterbook-fr
  artifacts:
    paths:
      - jupyterbook-de/_build/
      - jupyterbook-fr/_build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv jupyterbook-de/_build/html public/de
    - mv jupyterbook-fr/_build/html public/fr

  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
