name: minicourse
channels:
  - defaults
dependencies:
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - bleach
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - libcxx
  - libffi
  - libsodium
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - openssl
  - packaging
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pip
  - prometheus_client
  - prompt-toolkit
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - readline
  - requests
  - send2trash
  - setuptools
  - six
  - sniffio
  - sqlite
  - stack_data
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
